### ISSUE TITLE
Could you publish this package to npm?

### ISSUE THREAD

**Issue by martinmicunda** [tomastrajan/jasmine-async-sugar#3]
Could you publish this package to npm? Thanks

**Comment by inthemill** [comment]
https://www.npmjs.com/package/jasmine-async-sugar
here it is.
happy depending :)

**Comment by martinmicunda** [comment]
Could you also push new version 1.3.0 to npm? Thanks

**Comment by inthemill** [comment]
Hi martinmicunda, can you please describe, how you are using this package with npm. As I am not sure how to use it with npm, I can not prepare the code to play well with it.

**Comment by martinmicunda** [comment]
@inthemill yeah here is the [project](https://github.com/martinmicunda/employee-scheduling-ui/blob/master/karma.conf.js#L23) where I am using this package with npm..

**Comment by inthemill** [comment]
I see. that means no special care for modules, node's global or jasmine-npm, 1.3.0 is on npm.

**Comment by martinmicunda** [comment]
Thanks
